ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.flip.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/flip"
    url = ${?DATABASE_URL}
    user = "flip"
    user = ${?DATABASE_USER}
    password = "flip"
    password = ${?DATABASE_PASSWORD}
}

storage {
    localPath = "./uploads"
    localPath = ${?STORAGE_PATH}
}
